### ISSUE TITLE
Allow blocks in custom input file

### ISSUE THREAD

**Issue by thierryseegers** [nacpatil/Genome_Cpp#11]
Currently, the custom input file allows only one set of numerical parameters and input `.bed` files unlike the JSON-formatted input file that allows multiple of these. Modify the parsing code to have the same feature for custom input files.

The parsing code can allow in both an implicit and an explicit way. The explicit way is to have a special character to declare the start of a new block. This character can be `$`. The implicit way is to assume that a block consists of numerical parameters followed by a list of input `.bed` file paths. If, after parsing file paths, a new numerical parameter is found, it signals the beginning of a new block.

**Comment by nacpatil** [comment]
I think it is complete now.
